name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get environmental variables
        env:
          PASSWORD: '${{ secrets.PASSWORD }}'
          GMAIL_ADDRESS: '${{ secrets.GMAIL_ADDRESS }}'
      - name: "Run python script"
        run: |
          python main.py
