name: GitHub Actions Secret

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get environmental variables
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          PASSWORD: ${{ secrets.PASSWORD }}
#         run: echo $GMAIL_ADDRESS $PASSWORD
          run: Personal\ Site\ -\ Bootstrap/main.py
