name: GitHub Actions Secret

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get environmental variables
        working-directory: .Personal Site - Bootstrap
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python Personal%20Site%20-%20Bootstrap/main.py
