name: GitHub Actions Secret

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get environmental variables
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        run: echo $PASSWORD $GMAIL_ADDRESS
